###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID localhost.localdomain)
#  Generated on:      Sat Oct 17 13:08:07 2020
#  Design:            filter
#  Command:           saveFPlan filter_start.fp
###############################################################

Version: 8

Head Box: 0.0000 0.0000 112.2900 110.8800
IO Box: 0.0000 0.0000 112.2900 110.8800
Core Box: 5.1300 5.0400 107.1600 105.8400
UseStdUtil: false

######################################################
#  DesignRoutingHalo: <space> <bottomLayerName> <topLayerName>
######################################################

######################################################
#  Core Rows Parameters:                             #
######################################################
Row Spacing = 0.000000
Row SpacingType = 2
Row Flip = 2
Core Row Site: FreePDK45_38x28_10R_NP_162NW_34O 

##############################################################################
#  DefRow: <name> <site> <x> <y> <orient> <num_x> <num_y> <step_x> <step_y>  #
##############################################################################
DefRow: ROW_0 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 5.0400 FS 537 1 0.1900 0.0000
DefRow: ROW_1 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 6.4400 N 537 1 0.1900 0.0000
DefRow: ROW_2 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 7.8400 FS 537 1 0.1900 0.0000
DefRow: ROW_3 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 9.2400 N 537 1 0.1900 0.0000
DefRow: ROW_4 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 10.6400 FS 537 1 0.1900 0.0000
DefRow: ROW_5 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 12.0400 N 537 1 0.1900 0.0000
DefRow: ROW_6 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 13.4400 FS 537 1 0.1900 0.0000
DefRow: ROW_7 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 14.8400 N 537 1 0.1900 0.0000
DefRow: ROW_8 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 16.2400 FS 537 1 0.1900 0.0000
DefRow: ROW_9 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 17.6400 N 537 1 0.1900 0.0000
DefRow: ROW_10 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 19.0400 FS 537 1 0.1900 0.0000
DefRow: ROW_11 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 20.4400 N 537 1 0.1900 0.0000
DefRow: ROW_12 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 21.8400 FS 537 1 0.1900 0.0000
DefRow: ROW_13 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 23.2400 N 537 1 0.1900 0.0000
DefRow: ROW_14 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 24.6400 FS 537 1 0.1900 0.0000
DefRow: ROW_15 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 26.0400 N 537 1 0.1900 0.0000
DefRow: ROW_16 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 27.4400 FS 537 1 0.1900 0.0000
DefRow: ROW_17 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 28.8400 N 537 1 0.1900 0.0000
DefRow: ROW_18 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 30.2400 FS 537 1 0.1900 0.0000
DefRow: ROW_19 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 31.6400 N 537 1 0.1900 0.0000
DefRow: ROW_20 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 33.0400 FS 537 1 0.1900 0.0000
DefRow: ROW_21 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 34.4400 N 537 1 0.1900 0.0000
DefRow: ROW_22 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 35.8400 FS 537 1 0.1900 0.0000
DefRow: ROW_23 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 37.2400 N 537 1 0.1900 0.0000
DefRow: ROW_24 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 38.6400 FS 537 1 0.1900 0.0000
DefRow: ROW_25 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 40.0400 N 537 1 0.1900 0.0000
DefRow: ROW_26 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 41.4400 FS 537 1 0.1900 0.0000
DefRow: ROW_27 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 42.8400 N 537 1 0.1900 0.0000
DefRow: ROW_28 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 44.2400 FS 537 1 0.1900 0.0000
DefRow: ROW_29 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 45.6400 N 537 1 0.1900 0.0000
DefRow: ROW_30 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 47.0400 FS 537 1 0.1900 0.0000
DefRow: ROW_31 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 48.4400 N 537 1 0.1900 0.0000
DefRow: ROW_32 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 49.8400 FS 537 1 0.1900 0.0000
DefRow: ROW_33 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 51.2400 N 537 1 0.1900 0.0000
DefRow: ROW_34 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 52.6400 FS 537 1 0.1900 0.0000
DefRow: ROW_35 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 54.0400 N 537 1 0.1900 0.0000
DefRow: ROW_36 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 55.4400 FS 537 1 0.1900 0.0000
DefRow: ROW_37 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 56.8400 N 537 1 0.1900 0.0000
DefRow: ROW_38 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 58.2400 FS 537 1 0.1900 0.0000
DefRow: ROW_39 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 59.6400 N 537 1 0.1900 0.0000
DefRow: ROW_40 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 61.0400 FS 537 1 0.1900 0.0000
DefRow: ROW_41 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 62.4400 N 537 1 0.1900 0.0000
DefRow: ROW_42 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 63.8400 FS 537 1 0.1900 0.0000
DefRow: ROW_43 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 65.2400 N 537 1 0.1900 0.0000
DefRow: ROW_44 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 66.6400 FS 537 1 0.1900 0.0000
DefRow: ROW_45 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 68.0400 N 537 1 0.1900 0.0000
DefRow: ROW_46 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 69.4400 FS 537 1 0.1900 0.0000
DefRow: ROW_47 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 70.8400 N 537 1 0.1900 0.0000
DefRow: ROW_48 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 72.2400 FS 537 1 0.1900 0.0000
DefRow: ROW_49 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 73.6400 N 537 1 0.1900 0.0000
DefRow: ROW_50 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 75.0400 FS 537 1 0.1900 0.0000
DefRow: ROW_51 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 76.4400 N 537 1 0.1900 0.0000
DefRow: ROW_52 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 77.8400 FS 537 1 0.1900 0.0000
DefRow: ROW_53 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 79.2400 N 537 1 0.1900 0.0000
DefRow: ROW_54 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 80.6400 FS 537 1 0.1900 0.0000
DefRow: ROW_55 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 82.0400 N 537 1 0.1900 0.0000
DefRow: ROW_56 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 83.4400 FS 537 1 0.1900 0.0000
DefRow: ROW_57 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 84.8400 N 537 1 0.1900 0.0000
DefRow: ROW_58 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 86.2400 FS 537 1 0.1900 0.0000
DefRow: ROW_59 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 87.6400 N 537 1 0.1900 0.0000
DefRow: ROW_60 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 89.0400 FS 537 1 0.1900 0.0000
DefRow: ROW_61 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 90.4400 N 537 1 0.1900 0.0000
DefRow: ROW_62 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 91.8400 FS 537 1 0.1900 0.0000
DefRow: ROW_63 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 93.2400 N 537 1 0.1900 0.0000
DefRow: ROW_64 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 94.6400 FS 537 1 0.1900 0.0000
DefRow: ROW_65 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 96.0400 N 537 1 0.1900 0.0000
DefRow: ROW_66 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 97.4400 FS 537 1 0.1900 0.0000
DefRow: ROW_67 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 98.8400 N 537 1 0.1900 0.0000
DefRow: ROW_68 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 100.2400 FS 537 1 0.1900 0.0000
DefRow: ROW_69 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 101.6400 N 537 1 0.1900 0.0000
DefRow: ROW_70 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 103.0400 FS 537 1 0.1900 0.0000
DefRow: ROW_71 FreePDK45_38x28_10R_NP_162NW_34O 5.1300 104.4400 N 537 1 0.1900 0.0000

############################################################################################
#  Track: dir start number space layer_num layer1 [firstColor] [isSameColor] [width] [rule]#
############################################################################################
Track: Y 1.9100 69 1.6000 1 10
Track: X 1.8650 66 1.6800 1 10
Track: X 1.0250 133 0.8400 1 9
Track: Y 1.9100 69 1.6000 1 9
Track: Y 0.9100 131 0.8400 1 8
Track: X 1.0250 133 0.8400 1 8
Track: X 0.1850 401 0.2800 1 7
Track: Y 0.9100 131 0.8400 1 7
Track: Y 0.3500 395 0.2800 1 6
Track: X 0.1850 401 0.2800 1 6
Track: X 0.1850 401 0.2800 1 5
Track: Y 0.3500 395 0.2800 1 5
Track: Y 0.0700 792 0.1400 1 4
Track: X 0.1850 401 0.2800 1 4
Track: X 0.0950 591 0.1900 1 3
Track: Y 0.0700 792 0.1400 1 3
Track: Y 0.0700 792 0.1400 1 2
Track: X 0.0950 591 0.1900 1 2
Track: X 0.0950 591 0.1900 1 1
Track: Y 0.0700 792 0.1400 1 1

######################################################
#  GCellGrid: dir start number space                 #
######################################################
GCellGrid: X 112.1950 2 0.0950
GCellGrid: X 0.0950 60 1.9000
GCellGrid: X 0.0000 2 0.0950
GCellGrid: Y 110.6700 2 0.2100
GCellGrid: Y 0.0700 80 1.4000
GCellGrid: Y 0.0000 2 0.0700

######################################################
#  SpareCell: cellName                               #
#  SpareInst: instName                               #
######################################################

###############################1p########################
#  <SelectiveBlockage>                                #
#     <cell name="cell_name" />                     #
#  </SelectiveBlockage                                #
#######################################################

######################################################
#  ScanGroup: groupName startPin stopPin             #
######################################################

######################################################
#  JtagCell:  leafCellName                           #
#  JtagInst:  <instName | HInstName>                 #
######################################################

#########################################################
#  PhysicalNet: <name> [-pwr|-gnd|-tiehi|-tielo]        #
#########################################################
PhysicalNet: VDD -pwr
PhysicalNet: VSS -gnd

#####################################################################################
# <PGNets>                                                                          #
#    <PGNet name="net_name">                                                        #
#       <HNet name="hnet_name">                                                     #
#          <Port hinst="hinst_name" name="port_name" direction="in|out|inout" />    #
#       </HNet>                                                                     #
#    </PGNet>                                                                       #
# </PGNets>                                                                         #
#####################################################################################

#########################################################
#  PhysicalInstance: <name> <cell> <orient> <llx> <lly> #
#########################################################

#####################################################################
#  Group: <group_name> <nrHinst> [-isPhyHier]                       #
#    <inst_name>                                                    #
#    ...                                                            #
#####################################################################

#####################################################################
#  Fence:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Region: <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Guide:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  SoftGuide: <name>                                                #
#    ...                                                            #
#####################################################################

###########################################################################
#  <Constraints>                                                          #
#     <Constraint  type="fence|guide|region|softguide"                    #
#                  readonly=1  name="blk_name">                           #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#     </Constraint>                                                       #
#  </Constraints>                                                         #
###########################################################################

###########################################################################
#  <MacroArrays>                                                          #
#      <MacroArray>                                                       #
#          ...                                                            #
#      </MacroArray>                                                      #
#      ...                                                                #
#  </MacroArrays>                                                         #
###########################################################################

######################################################################################
#  BlackBox: -cell <cell_name> { -size <x> <y> |  -area <um^2> | \                  #
#            -gatecount <count> <areapergate> <utilization> | \                     #
#            {-gateArea <gateAreaValue> [-macroArea <macroAreaValue>]} } \          #
#            [-minwidth <w> | -minheight <h> | -fixedwidh <w> | -fixedheight <h>] \ #
#            [-aspectratio <ratio>]                                                  #
#            [-boxList <nrConstraintBox>                                             #
#              ConstraintBox: <llx> <lly> <urx> <ury>                                #
#              ... ]                                                                 #
######################################################################################

#######################################################################################
#  <Blackboxes>                                                                       #
#     <Blackbox  cell=name  width=N height=N                                          #
#                { area=A | gatecount=N areaPerGate=A cellUtil=F |                    #
#                  gateArea=F {macroArea=F | macorList='str'} includeMacroArea={0|1}} #
#                [minWidth=N | minHeight=N | fixedWidh=N | fixedHeight=N]             #
#                [aspectRatio=R] >                                                    #
#         <Box llx=float lly=float urx=float ury=float /> ...                         #
#     </Blackbox>                                                                     #
#  </Blackboxes>                                                                      #
#######################################################################################

######################################################
#  Instance: <name> <orient> <llx> <lly>             #
######################################################

#################################################################
#  Block: <name> <orient> [<llx> <lly>]                         #
#         [<haloLeftMargin>  <haloBottomMargin>                 #
#          <haloRightMargin> <haloTopMargin> <haloFromInstBox>] #
#         [<IsInstDefCovered> <IsInstPreplaced>]                #
#                                                               #
#  Block with INT_MAX loc is for recording the halo block with  #
#  non-prePlaced status                                         #
#################################################################

###########################################################################
#  BlockRoutingHalo: <name> <space> <bottomLayer> <topLayer> <-lithoHalo> #
###########################################################################

######################################################
#  BlockLayerObstruct: <name> <layerX> ...           #
######################################################

######################################################
#  FeedthroughBuffer: <instName>                     #
######################################################

###########################################################################
#  <HierarchicalPartitions>                                               #
#     <GlobalPinConstraints>                                              #
#         <PinSpacing spacing=val />                                      #
#         <PinWidth layer=layerId width=val />                            #
#         <PinDepth layer=layerId depth=val />                            #
#         <CornerToPinDistance distance=val />                            #
#     </GlobalPinConstraints>                                             #
#     <CellPtnCut name="name" cuts=Num >                                  #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 /> ...                  #
#     </CellPtnCut>                                                       #
#     <NetGroup name="group_name" nets=val spacing=val isOptOrder=val   #
#         isAltLayer=val isPffGroup=val isSpreadPin=val                   #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val isMixedSignal=val >         #
#         <Net name="net_name" /> ...                                   #
#     </NetGroup>                                                         #
#     <Partition name="ptn_name"  hinst="name"                            #
#         coreToLeft=fval coreToRight=fval coreToTop=fval                 #
#         coreToBottom=val pinSpacingNorth=val pinSpacingWest=val         #
#         pinSpacingSouth=val pinSpacingEast=val  blockedLayers=xval >    #
#         <TrackHalfPitch Horizontal=val Vertical=val />                  #
#         <SpacingHalo left=10.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <Clone hinst="hinst_name" orient=R0|R90|... />                  #
#         <PinLayer side="N|W|S|E" Metal1=yes Metal2=yes ... />           #
#         <RowSize cellHeight=1.0 railWidth=1.0 />                        #
#         <DefaultTechSite name="core" />                                   #
#         <RoutingHalo sideSize=11.0 bottomLayer=M1 topLayer=M2  />       #
#         <SpacingHalo left=11.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <PinToCornerDistance  totalCorners=nrCorners >                  #
#            <Corner number=<cornerNumber> distance=<distance> /> ...     #
#         </PinToCornerDistance >                                         #
#         <PinSpacingArea llx=val lly=val urx=val ury=val spacing=val />  #
#         <LayerWidthDepth layer=layerId width=w depth=d />               #
#         <PinConstraint>                                                 #
#            <Pin name="pinName" >                                      #
#               <edge2 edgeMap=val />                                    #
#               <spacing space=val />                                    #
#               <layer layerMap=xval />                                  #
#               <pinWidth width=val />                                   #
#               <pinDepth depth=val />                                   #
#               <location x=val y=val />                                 #
#            </Pin>                                                       #
#         </PinConstraint>                                                #
#     </Partition>                                                        #
#     <CellPinGroup name="group_name" cell="cell_name" pins=nr        #
#         spacing=val isOptOrder=val isAltLayer=val isSpreadPin=val       #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val >                           #
#         <GroupFTerm name="term_name" /> ...                             #
#     </CellPinGroup>                                                     #
#     <PartitionPinBlockage layerMap=x llx=1 lly=2 urx=3 ury=4 name="n" />#
#     <PinGuide name="name" boxes=num layerPriority=val cell="name" >     #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 layer=id /> ...         #
#     </PinGuide>                                                         #
#  </HierarchicalPartitions>                                              #
###########################################################################
<HierarchicalPartitions>
    <GlobalPinConstraints>
        <PinSpacing spacing=2 />
        <CornerToPinDistance distance=5 />
    </GlobalPinConstraints>
    <Partition name="filter" hinst="" coreToLeft=0.0000 coreToRight=0.0000 coreToTop=0.0000 coreToBottom=0.0000 pinSpacingNorth=-1 pinSpacingWest=-1 pinSpacingSouth=-1 pinSpacingEast=-1 blockedLayers=0x3ff orient=R0>
	<PinLayer side="N" Metal2=yes Metal4=yes Metal6=yes Metal8=yes Metal10=yes />
	<PinLayer side="W" Metal3=yes Metal5=yes Metal7=yes Metal9=yes />
	<PinLayer side="S" Metal2=yes Metal4=yes Metal6=yes Metal8=yes Metal10=yes />
	<PinLayer side="E" Metal3=yes Metal5=yes Metal7=yes Metal9=yes />
    <PinToCornerDistance totalCorners=4 >
      <Corner number=0 distance=-1 />
      <Corner number=1 distance=-1 />
      <Corner number=2 distance=-1 />
      <Corner number=3 distance=-1 />
    </PinToCornerDistance>
    </Partition>
</HierarchicalPartitions>

####################################################################################
#  <PlacementBlockages>                                                            #
#     <Blockage name="blk_name" type="hard|soft|partial">                      #
#       <Attr density=1.2 excludeFlops=yes inst="inst_name" pushdown=yes />      #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                        #
#     </Blockage>                                                                  #
#  </PlacementBlockages>                                                           #
####################################################################################

#################################################################
#  <SizeBlockages>                                             #
#     <Blockage name="blk_name">                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </SizeBlockages>                                            #
#################################################################

##########################################################################################################
#  <RouteBlockages>                                                                                      #
#     <Blockage name="blk_name" type="User|RouteGuide|PtnCut|WideWire">                              #
#       <Attr spacing=1.2 drw=1.2 inst="name" pushdown=yes fills=yes exceptpgnet=yes pgnetonly=yes />  #
#       <Layer type="route|cut|masterslice" id=layerNo />                                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                                              #
#       <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...  />                                                      #
#     </Blockage>                                                                                        #
#  </RouteBlockages>                                                                                     #
##########################################################################################################

######################################################
#  NetWeight: <net_name> <weight (in integer)>       #
######################################################

###########################################################################################
# NetbottomPreferredRoutingLayer:  <net_name> <bottomPreferredRoutingLayer (in integer)>  #
###########################################################################################

################################################################
# NetAvoidDetour:  <net_name>  < avoidDetour  { 1| 0}>   #
################################################################

#################################################################
#  SprFile: <file_name>                                         #
#################################################################
SprFile: filter_start.fp.spr

##############################################################################
#  <IOPins>                                                                  #
#    <Pin name="pin_name" type="clock|power|ground|analog"                   #
#         status="covered|fixed|placed" is_special=1 >                       #
#      <Port>                                                                #
#        <Pref x=1 y=2 side="N|S|W|E|U|D" width=w depth=d orientation=val /> #
#        <Via name="via_name" x=1 y=2 BotMask=2 CutMask=1 TopMask=2 />...  #
#        <Layer id=id spacing=1.2 drw=1.2>                                   #
#          <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#          <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...           />              #
#        </Layer> ...                                                        #
#      </Port>  ...                                                          #
#      <NETEXPR>                                                             #
#        ground VSS                                                          #
#      </NETEXPR> ...                                                        #
#      <Antenna model=num type="name" value=float_num layer=num /> ...       #
#    </Pin> ...                                                              #
#  </IOPins>                                                                 #
##############################################################################

<IOPins>
  <Pin name="VIN" >
  </Pin>
  <Pin name="RST_n" >
  </Pin>
  <Pin name="CLK" >
  </Pin>
  <Pin name="DIN[11]" >
  </Pin>
  <Pin name="DIN[10]" >
  </Pin>
  <Pin name="DIN[9]" >
  </Pin>
  <Pin name="DIN[8]" >
  </Pin>
  <Pin name="DIN[7]" >
  </Pin>
  <Pin name="DIN[6]" >
  </Pin>
  <Pin name="DIN[5]" >
  </Pin>
  <Pin name="DIN[4]" >
  </Pin>
  <Pin name="DIN[3]" >
  </Pin>
  <Pin name="DIN[2]" >
  </Pin>
  <Pin name="DIN[1]" >
  </Pin>
  <Pin name="DIN[0]" >
  </Pin>
  <Pin name="B0[11]" >
  </Pin>
  <Pin name="B0[10]" >
  </Pin>
  <Pin name="B0[9]" >
  </Pin>
  <Pin name="B0[8]" >
  </Pin>
  <Pin name="B0[7]" >
  </Pin>
  <Pin name="B0[6]" >
  </Pin>
  <Pin name="B0[5]" >
  </Pin>
  <Pin name="B0[4]" >
  </Pin>
  <Pin name="B0[3]" >
  </Pin>
  <Pin name="B0[2]" >
  </Pin>
  <Pin name="B0[1]" >
  </Pin>
  <Pin name="B0[0]" >
  </Pin>
  <Pin name="B1[11]" >
  </Pin>
  <Pin name="B1[10]" >
  </Pin>
  <Pin name="B1[9]" >
  </Pin>
  <Pin name="B1[8]" >
  </Pin>
  <Pin name="B1[7]" >
  </Pin>
  <Pin name="B1[6]" >
  </Pin>
  <Pin name="B1[5]" >
  </Pin>
  <Pin name="B1[4]" >
  </Pin>
  <Pin name="B1[3]" >
  </Pin>
  <Pin name="B1[2]" >
  </Pin>
  <Pin name="B1[1]" >
  </Pin>
  <Pin name="B1[0]" >
  </Pin>
  <Pin name="B2[11]" >
  </Pin>
  <Pin name="B2[10]" >
  </Pin>
  <Pin name="B2[9]" >
  </Pin>
  <Pin name="B2[8]" >
  </Pin>
  <Pin name="B2[7]" >
  </Pin>
  <Pin name="B2[6]" >
  </Pin>
  <Pin name="B2[5]" >
  </Pin>
  <Pin name="B2[4]" >
  </Pin>
  <Pin name="B2[3]" >
  </Pin>
  <Pin name="B2[2]" >
  </Pin>
  <Pin name="B2[1]" >
  </Pin>
  <Pin name="B2[0]" >
  </Pin>
  <Pin name="B3[11]" >
  </Pin>
  <Pin name="B3[10]" >
  </Pin>
  <Pin name="B3[9]" >
  </Pin>
  <Pin name="B3[8]" >
  </Pin>
  <Pin name="B3[7]" >
  </Pin>
  <Pin name="B3[6]" >
  </Pin>
  <Pin name="B3[5]" >
  </Pin>
  <Pin name="B3[4]" >
  </Pin>
  <Pin name="B3[3]" >
  </Pin>
  <Pin name="B3[2]" >
  </Pin>
  <Pin name="B3[1]" >
  </Pin>
  <Pin name="B3[0]" >
  </Pin>
  <Pin name="B4[11]" >
  </Pin>
  <Pin name="B4[10]" >
  </Pin>
  <Pin name="B4[9]" >
  </Pin>
  <Pin name="B4[8]" >
  </Pin>
  <Pin name="B4[7]" >
  </Pin>
  <Pin name="B4[6]" >
  </Pin>
  <Pin name="B4[5]" >
  </Pin>
  <Pin name="B4[4]" >
  </Pin>
  <Pin name="B4[3]" >
  </Pin>
  <Pin name="B4[2]" >
  </Pin>
  <Pin name="B4[1]" >
  </Pin>
  <Pin name="B4[0]" >
  </Pin>
  <Pin name="B5[11]" >
  </Pin>
  <Pin name="B5[10]" >
  </Pin>
  <Pin name="B5[9]" >
  </Pin>
  <Pin name="B5[8]" >
  </Pin>
  <Pin name="B5[7]" >
  </Pin>
  <Pin name="B5[6]" >
  </Pin>
  <Pin name="B5[5]" >
  </Pin>
  <Pin name="B5[4]" >
  </Pin>
  <Pin name="B5[3]" >
  </Pin>
  <Pin name="B5[2]" >
  </Pin>
  <Pin name="B5[1]" >
  </Pin>
  <Pin name="B5[0]" >
  </Pin>
  <Pin name="B6[11]" >
  </Pin>
  <Pin name="B6[10]" >
  </Pin>
  <Pin name="B6[9]" >
  </Pin>
  <Pin name="B6[8]" >
  </Pin>
  <Pin name="B6[7]" >
  </Pin>
  <Pin name="B6[6]" >
  </Pin>
  <Pin name="B6[5]" >
  </Pin>
  <Pin name="B6[4]" >
  </Pin>
  <Pin name="B6[3]" >
  </Pin>
  <Pin name="B6[2]" >
  </Pin>
  <Pin name="B6[1]" >
  </Pin>
  <Pin name="B6[0]" >
  </Pin>
  <Pin name="B7[11]" >
  </Pin>
  <Pin name="B7[10]" >
  </Pin>
  <Pin name="B7[9]" >
  </Pin>
  <Pin name="B7[8]" >
  </Pin>
  <Pin name="B7[7]" >
  </Pin>
  <Pin name="B7[6]" >
  </Pin>
  <Pin name="B7[5]" >
  </Pin>
  <Pin name="B7[4]" >
  </Pin>
  <Pin name="B7[3]" >
  </Pin>
  <Pin name="B7[2]" >
  </Pin>
  <Pin name="B7[1]" >
  </Pin>
  <Pin name="B7[0]" >
  </Pin>
  <Pin name="B8[11]" >
  </Pin>
  <Pin name="B8[10]" >
  </Pin>
  <Pin name="B8[9]" >
  </Pin>
  <Pin name="B8[8]" >
  </Pin>
  <Pin name="B8[7]" >
  </Pin>
  <Pin name="B8[6]" >
  </Pin>
  <Pin name="B8[5]" >
  </Pin>
  <Pin name="B8[4]" >
  </Pin>
  <Pin name="B8[3]" >
  </Pin>
  <Pin name="B8[2]" >
  </Pin>
  <Pin name="B8[1]" >
  </Pin>
  <Pin name="B8[0]" >
  </Pin>
  <Pin name="DOUT[11]" >
  </Pin>
  <Pin name="DOUT[10]" >
  </Pin>
  <Pin name="DOUT[9]" >
  </Pin>
  <Pin name="DOUT[8]" >
  </Pin>
  <Pin name="DOUT[7]" >
  </Pin>
  <Pin name="DOUT[6]" >
  </Pin>
  <Pin name="DOUT[5]" >
  </Pin>
  <Pin name="DOUT[4]" >
  </Pin>
  <Pin name="DOUT[3]" >
  </Pin>
  <Pin name="DOUT[2]" >
  </Pin>
  <Pin name="DOUT[1]" >
  </Pin>
  <Pin name="DOUT[0]" >
  </Pin>
  <Pin name="VOUT" >
  </Pin>
</IOPins>

#####################################################################
#  <Property>                                                       #
#     <obj_type name="inst_name" >                                  #
#       <prop name="name" type=type_name value=val />               #
#       <Attr name="name" type=type_name value=val />               #
#     </obj_type>                                                   #
#  </Property>                                                      #
#  where:                                                           #
#       type is data type: Box, String, Int, PTR, Loc, double, Bits #
#       obj_type are: inst, Design, instTerm, Bump, cell, net       #
#####################################################################
<Properties>
  <Design name="filter">
  </Design>
</Properties>

################################################################################
#  NetProperties: <net_name> [-special] [-def_prop {int|dbl|str} <value>]...   #
################################################################################

##################################################################################
#    Feedthru info:                                                              #
# <Feedthrus>                                                                    #
#   <Feedthru>                                                                   #
#       <tsv llx=n lly=n urx=n ury=n />                                          #
#       <stackvia layer=z llx=n lly=n urx=n ury=n />                             #
#       <bump front=name back=name  />                                           #
#   </Feedthru>                                                                  #
#   <Feedthru>                                                                   #
#   <...>                                                                        #
#   </Feedthru>                                                                  #
# </Feedthrus>                                                                   #
################################################################################
